###
GET http://localhost:8080/cars

###
@id = 2
GET http://localhost:8080/cars/{{id}}

###
@name = L
GET http://localhost:8080/cars?name={{name}}

###
POST http://localhost:8080/cars
Content-Type: application/json

{
  "name": "288ALP"
}

###
PUT http://localhost:8080/cars/{{id}}
Content-Type: application/json

{
  "name": "22"
}


###
DELETE http://localhost:8080/cars/1

###
POST http://localhost:8080/clients
Content-Type: application/json

{
  "name": "Ismail"
}