###
GET http://localhost:8080/cars

###
@id = 1
GET http://localhost:8080/cars/{{id}}

###
@name = 169
GET http://localhost:8080/cars?name={{name}}

###
POST http://localhost:8080/cars
Content-Type: application/json

{
  "name": "169ANL"
}

###
PUT http://localhost:8080/cars/{{id}}
Content-Type: application/json

{
  "name": "554ALO"
}


###
DELETE http://localhost:8080/cars/1